<a href="https://colab.research.google.com/github/prathi-mani/Reinforcement-learning-study-group/blob/main/SARSA_and_Q_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
! pip install gymnasium

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 953.8/953.8 kB 17.2 MB/s eta 0:00:00


In [7]:
import gymnasium as gym
import numpy as np
import matplotlib.pyplot as plt


In [52]:
import numpy as np
import gym

# Set up the environment
env = gym.make('FrozenLake-v1')

# Initialize Q-table with zeros
Q = np.zeros([env.observation_space.n, env.action_space.n])

# Set parameters
num_episodes = 5000
learning_rate = 0.85
gamma = 0.95
epsilon = 1.0
epsilon_decay = 0.999
cumulative_rewards = []
# SARSA
for i in range(num_episodes):
    # Reset the state
    state = env.reset()
    action = np.argmax(Q[state,:] + np.random.randn(1, env.action_space.n) * (1. / (i+1)))
    cumulative_reward = 0
    for j in range(100):
        # Perform action and get new state & reward
        new_state, reward, done, _ = env.step(action)
        cumulative_reward += reward
        # Select new action
        new_action = np.argmax(Q[new_state,:] + np.random.randn(1, env.action_space.n) * (1. / (i+1)))

        # Update Q-Table
        Q[state, action] = Q[state, action] + learning_rate * (reward + gamma * Q[new_state, new_action] - Q[state, action])

        state = new_state
        action = new_action

        if done:
            epsilon *= epsilon_decay
            break
    cumulative_rewards.append(cumulative_reward)

print("Q-Table")
print(Q)

print("Cumulative rewards")
print(cumulative_rewards)

Q-Table
[[1.98270173e-02 5.00282272e-05 3.42094654e-04 1.62984418e-04]
 [2.82265671e-05 3.19012243e-05 1.72307235e-06 5.15757467e-02]
 [1.76421334e-05 6.72522743e-06 3.34524195e-05 8.14913291e-02]
 [1.02982878e-10 1.03639677e-04 7.34739864e-06 5.95326171e-02]
 [1.38405180e-02 4.57048697e-04 4.55002021e-07 8.35045519e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.08205279e-01 2.79363504e-06 8.27588368e-05 3.79783408e-07]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.92262744e-05 1.10183251e-03 1.98163914e-04 2.68738540e-02]
 [0.00000000e+00 1.22864771e-01 6.58469717e-05 6.45462838e-05]
 [1.83412948e-01 5.20943416e-05 6.83672609e-05 4.17053290e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.30683480e-02 7.49465063e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 8.80502650e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 